INSERT INTO PHONES (NAME, BRAND, PRICE, CURR) VALUES ('Galaxy S23 Ultra', 'Samsung', 999.99, 'EUR');
INSERT INTO PHONES (NAME, BRAND, PRICE, CURR) VALUES ('13 Pro', 'Xiaomi', 799.99, 'EUR');
INSERT INTO PHONES (NAME, BRAND, PRICE, CURR) VALUES ('iPhone 14', 'Apple', 1099.99, 'EUR');
INSERT INTO PHONES (NAME, BRAND, PRICE, CURR) VALUES ('Pixel 8', 'Google', 899.99, 'EUR');
INSERT INTO PHONES (NAME, BRAND, PRICE, CURR) VALUES ('Pixel 7', 'Google', 759.99, 'EUR');
INSERT INTO PHONES (NAME, BRAND, PRICE, CURR) VALUES ('Pixel 7a', 'Google', 599.99, 'EUR');